#include "arduino_secrets.h"
// DHT sensor library - Version: Latest 
#include <DHT.h>
#include <DHT_U.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "R4 WIFY"
  https://create.arduino.cc/cloud/things/bcc24f66-c6e5-46a4-b3f1-2ed1d4fb5a0e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temp;
  float umidita;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"

#define DHTPIN 2 
#define DHTTYPE DHT11
DHT dht(DHTPIN, DHTTYPE);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  dht.begin();
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  float h = dht.readHumidity();
  Serial.print(h);
  umidita = h;

  float t = dht.readTemperature();
  Serial.print(t);
  Serial.print("\n");
  temp = t;
  delay(1000);
}

/*
  Since D is READ_WRITE variable, onDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDChange()  {
  // Add your code here to act upon D change
}
/*
  Since Temp is READ_WRITE variable, onTempChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTempChange()  {
  // Add your code here to act upon Temp change
}
/*
  Since Umidita is READ_WRITE variable, onUmiditaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onUmiditaChange()  {
  // Add your code here to act upon Umidita change
}
